### ISSUE TITLE
plugin doesn't work with latest swc

### ISSUE THREAD

**Issue by Hotell** [bsunderhus/swc-plugin-de-indent-template-literal#1]
Context:

https://github.com/microsoft/fluentui/pull/30620/files#r1504727678

**Priority:** high

**Comment by bsunderhus** [comment]
Seems like [swc/core v1.4.0](https://github.com/swc-project/swc/releases/tag/v1.4.0) requires rust's swc_core of v0.90.0.

We're currently using v0.79.0, I'll see to add a `peerDependencies` to make this more explicit and also release a version that is compatible with the latest `swc_core`

**Comment by bsunderhus** [comment]
This should be resolved by https://github.com/bsunderhus/swc-plugin-de-indent-template-literal/commit/41f52ba011f04a8fa16d2ee058b012afd6a19829, @Hotell  can you confirm? (the plugin v1.4.0 is already published and should be compatible with the latest swc version)
